<Uran>:
    angle: 0
    size_hint: None, None
    pos: self.x,self.y
    background_color: 0, 0, 0, 0


    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center

        Color:
            rgba: (1,1,1,1)

        Rectangle:
            size: self.width, self.height
            pos: self.x, self.y

    canvas.after:
        PopMatrix
        Color:
            rgba: (0,1,0,0)


